/* eslint-disable */
// This base model was auto-generated by export_app
// PLEASE DO NOT EDIT
// you can make changes in app/models/list/listitem.js
// or regenerate this file by running
// `./manage.py export list/listitems`

  import Model from 'ember-data/model';


import attr from 'ember-data/attr';


import { hasMany } from 'ember-data/relationships';


export default Model.extend({
  
    description: attr('string'),
  
    done: attr('boolean'),
  
    __str__: attr('string'),
  
  
    todo: hasMany('list/list', {
      async: true,
      inverse: 'description',
    }),
  
});
