# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-30 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('done', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='list.ListItem'),
        ),
    ]
