# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-28 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20180330_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='description',
        ),
        migrations.AddField(
            model_name='listitem',
            name='lst',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='list.List'),
            preserve_default=False,
        ),
    ]
