# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-07 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20180728_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listitem',
            options={'ordering': ['-description']},
        ),
    ]
