// This base model was auto-generated by export_app
// PLEASE DO NOT EDIT
// you can make changes in app/models/to_do_list/day.js
// or regenerate this file by running
// `./manage.py export to-do-list/days`

import Model from 'ember-data/model';

import attr from 'ember-data/attr';


import { hasMany } from 'ember-data/relationships';


export default Model.extend({
  
    type: attr('string'),
  
    day_of_week: attr('string'),
  
    __str__: attr('string'),
  
  
    templates: hasMany('to_do_list/templatetask', {
      async: true,
      inverse: 'day'
    }),
  
});
