// This base model was auto-generated by export_app
// PLEASE DO NOT EDIT
// you can make changes in app/models/to_do_list/taskinstance.js
// or regenerate this file by running
// `./manage.py export to-do-list/taskinstances`

import Model from 'ember-data/model';

import attr from 'ember-data/attr';


import { belongsTo } from 'ember-data/relationships';


export default Model.extend({
  
    done: attr('boolean'),
  
    date: attr('string'),
  
    __str__: attr('string'),
  
  
    task: belongsTo('to_do_list/templatetask', {
      async: true,
      inverse: 'instance'
    }),
  
});
