// This base model was auto-generated by export_app
// PLEASE DO NOT EDIT
// you can make changes in app/models/to_do_list/templatetask.js
// or regenerate this file by running
// `./manage.py export to-do-list/templatetasks`

import Model from 'ember-data/model';

import attr from 'ember-data/attr';


import { belongsTo, hasMany } from 'ember-data/relationships';


export default Model.extend({
  
    description: attr('string'),
  
    updatable: attr('boolean'),
  
    __str__: attr('string'),
  
  
    instance: hasMany('to_do_list/taskinstance', {
      async: true,
      inverse: 'task'
    }),
  
    room: belongsTo('to_do_list/room', {
      async: true,
      inverse: 'templates'
    }),
  
    day: belongsTo('to_do_list/day', {
      async: true,
      inverse: 'templates'
    }),
  
});
